FROM node:lts-alpine as build-stage
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm i
RUN npm i -g @vue/cli
COPY . .
RUN npm run build

FROM nginx:stable-alpine as prod-stage
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
