version: '3.7'
services:
  nginx:
    container_name: micro_stock_client
    build:
      context: ./../client/
      dockerfile: ./../ci/Dockerfile.nginx
    ports: 
      - 80:80
      - 443:443

  cog-db:
    container_name: micro_cog_auth_db
    image: mongo:latest
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: rajesh
      MONGO_INITDB_ROOT_PASSWORD: rajesh
      MONGO_INITDB_DATABASE: cognito_auth
    volumes: 
      - ./../cognito-server/cognito-data:/data/db
      # - ./../cognito-server/cognito-data/init-db/:/docker-entrypoint-initdb.d/
    ports: 
      - "27017:27017"

  cog_server:
    container_name: micro_cog_auth_server
    build:
      context: ./../cognito-server/
      dockerfile: ./../ci/Dockerfile.cognito-server
    restart: always
    ports:
      - "8080:3000"
    depends_on: 
      - cog-db
    environment: 
      - DB_HOST=cognito-db
      - DB_PORT=27017
      - DB_NAME=auth
      - DB_USERNAME=rajesh
      - DB_PASSWORD=rajesh
    volumes: 
      - ./../cognito-server:/app
    # command: npm run prod

  scm:
    container_name: micro_scm
    build: 
      context: ./../stock-currency-manager
      dockerfile: ./../ci/Dockerfile.stock-currency-manager
    environment: 
      - RS_PROFILE=
      - DB_HOST=scm_db
      - DB_USERNAME=prod
      - DB_PASSWORD=1234
    ports: 
      - "8082:8080"
    depends_on: 
      - scm_db

  scm_db:
    container_name: micor_scm_db
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=prod
      - POSTGRES_DB=wallet
    
